### ISSUE TITLE
Questions about 10/13-selective-prediction

### ISSUE THREAD

**Issue by songmh99** [yuanmu97/tech-in-papers#1]
1. 为什么根据 `“从图中看到，大概结果是 x=0 y=0.675”` ，就可以得到结论 “`那么一个完美的 deferring 策略（或者称为输入过滤策略）应该是：当过滤 10% 的问题时，希望这些问题都是那些模型没有回答正确的问题，则最优的曲线应为：`”？
2.  为什么 认为 `“另外一个参考就是函数 y=0.325x+0.675，是接近 random 的过滤效果”` ？

**Comment by yuanmu97** [comment]
1. “当过滤10%问题时”是笔误，我会改成“过滤x比例问题时”；x=0 时，所有问题都回答了，y=0.675 代表 67.5% 的问题回答对了。那么最优情况下，过滤掉x比例问题，则回答的问题总量是 1-x，所以分母是 1-x；最优情况下没有把那些会回答正确的问题过滤，则仍然是0.675的问题回答正确，所以曲线是 0.675/(1-x)；

2. 这个地方我一开始写错了，感谢指出。我已经改成了如下表述：
另外一个参考就是函数 y=0.325x+0.675，这个函数本应该是表示 random 过滤后，在**全部问题上的精度**。这样理解，0.675能够回答正确的问题，不管过滤还是没过滤，我们都认为结果是对的；0.325回答不对的问题，只有过滤掉的时候认为结果是对的。所以过滤 x 比例的问题时，精度是 0.675+0.325x

实际上这两个指标是不可比的。但很神奇的是，论文的结果中的确和第二个参考线高度重叠。由于论文没有做其他关于 deferring performance 的验证，所以不太好分析原因。我希望不是他们对 metric 表述或计算错误 :)

**Comment by songmh99** [comment]
明白了 感谢您的回复
